version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
- cmd: nuget restore

build:
  project: RedStar.Amounts.sln
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: ouLeNlwj6D5dKMVTC4osrDgDvHHOJJTJSLXKYhuy5qbjavXQ07afHo+Z3SFDkYua
  skip_symbols: false